### ISSUE TITLE
StateUpdater interface should be removed

### ISSUE THREAD

**Issue by yangyangyyy** [jsprit/jsprit#141]
it seems pretty bad software design. an interface with no signature (methods) has no reason to exist.

the place where it's most prominently used is StateManager.addStateUpdater(StateUpdater param)

inside this function the param is checked against a bunch of  types and the behavior determined. if this is the intended logic, the addStateUpdater() method should be changed and split into the corresponding methods like addActivityVisitor() addReverseActivityVisitor() .....       I mean types exist for a reason, if it provides no information, it should be removed, otherwise it simply causes confusion.

**Comment by oblonski** [comment]
for now I leave StateUpdate as it is
