### ISSUE TITLE
time window constraint broken

### ISSUE THREAD

**Issue by oblonski** [jsprit/jsprit#146]
vehicle time windows (and possibly stop time windows too) sometimes being ignored for problems with shipments. A vehicle has stops after its end time window.

**Comment by PGWelch** [comment]
Thanks Stefan! I did a quick test and it looks good : )

Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.


Email: info@opendoorlogistics.com
Linkedin:  http://uk.linkedin.com/in/welchphilip
Skype: opendoorlogistics
Tel:  +44 (0) 20 8144 4009
Website:  http://www.opendoorlogistics.com






---- On Wed, 04 Feb 2015 07:48:30 +0000 Stefan Schröder &lt;notifications@github.com&gt; wrote ---- 

Closed #146.
