### ISSUE TITLE
Example on website uses deprecated setStartLocationCoordinate method

### ISSUE THREAD

**Issue by renanmzmendes** [jsprit/jsprit#147]
I'm actually trying to figure out what is the correct and not so verbose way of setting the start location coordinate, for the quick start on the website uses a deprecated method `setStartLocationCoordinate`

**Comment by oblonski** [comment]
Either you use .setStartLocationCoordinate(Coordinate.newInstance(x,y))
which is the way to go in the latest release OR
you use
.setStartLocation(Location.Builder.newInstance().setCoordinate(Coordinate.newInstance(x,y)).build())
which is the way you need to set Coordinates in the next release (already
implemented in the master branch - latest snapshot which you probably use
when the "old" method appears deprecated).

**Comment by renanmzmendes** [comment]
Hm, my bad. I should not have used the master branch... Well at least we know that this should be changed in the website when the new version is released. :-)

Thanks
