### ISSUE TITLE
Ignore Commute

### ISSUE THREAD

**Issue by demonicmetalcs** [jsprit/jsprit#149]
Hi,
I am looking for a way to ignore the commute.
So if a vehicle has a EarliestStart of 8 his first job will start at 8, And not that he starts driving to that location at 8. Same for the and time.
but i still want to use the start coordinate's.

Is there an easy way to do this?

**Comment by oblonski** [comment]
Do you mean variable start times? If so, there is currently no easy way.
You can do it as sort of post-process, i.e. optimize it it the ordinary
way and then modify the start times of your vehicles such that they do
not need to wait at the first activity (i.e. start_time =
earliest_start_first_act - travel_time(start,first_act). The problem
here is, that you loose some optimization potential compared to
considering variable start-times in the optimization. If you want to
consider it in the optimization, you need to modify the marginal cost
calculator (LocalActivityInsertionCalculator).
 

Am 02/03/15 um 12:27 schrieb demonicmetalcs:

**Comment by demonicmetalcs** [comment]
I have made a costmatrix that ignores the start commute.
i use the TransportDistance as calculated an set the TransportTime to zero for the cost from the start location
