### ISSUE TITLE
Capacity constraint problem when using PickupService and DeliverService

### ISSUE THREAD

**Issue by zach-m** [jsprit/jsprit#150]
Simple scenario:
- 1 vehicle with single-dimension capacity limit of 1
- 3 PickupService jobs with size 1
- 3 DeliverService jobs with size 1
- No bounding time or skills restrictions

Solution always returns 1 pickup + 1 delivery (instead of p + d + p + d + p + d, or so)
I noticed what appears to be a suspicious double-inversion in `ServiceLoadActivityLevelConstraint` line 70:

    if(newAct instanceof DeliverService){
        if(!Capacity.addup(Capacity.invert(..

Following is the entire problem.xml:

    <?xml version="1.0" encoding="UTF-8"?>
    <problem xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com vrp_xml_schema.xsd">
         <problemType>
              <fleetSize>FINITE</fleetSize>
         </problemType>
         <vehicles>
              <vehicle>
                   <id>v</id>
                   <typeId>vvt-v</typeId>
                   <startLocation>
                        <id>[x=0.0][y=0.0]</id>
                        <coord x="0.0" y="0.0"/>
                   </startLocation>
                   <endLocation>
                        <id>[x=0.0][y=0.0]</id>
                        <coord x="0.0" y="0.0"/>
                   </endLocation>
                   <timeSchedule>
                        <start>0.0</start>
                        <end>9.223372036854776E15</end>
                   </timeSchedule>
                   <returnToDepot>false</returnToDepot>
              </vehicle>
         </vehicles>
         <vehicleTypes>
              <type>
                   <id>vvt-v</id>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <costs>
                        <fixed>0.0</fixed>
                        <distance>1.0</distance>
                        <time>0.0</time>
                   </costs>
              </type>
         </vehicleTypes>
         <services>
              <service id="pick1" type="pickup">
                   <location>
                        <id>A1</id>
                        <coord x="500.0" y="0.0"/>
                   </location>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <duration>1000.0</duration>
                   <timeWindows>
                        <timeWindow>
                             <start>0.0</start>
                             <end>82800.0</end>
                        </timeWindow>
                   </timeWindows>
              </service>
              <service id="pick2" type="pickup">
                   <location>
                        <id>B1</id>
                        <coord x="-250.0" y="433.0"/>
                   </location>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <duration>1000.0</duration>
                   <timeWindows>
                        <timeWindow>
                             <start>0.0</start>
                             <end>82800.0</end>
                        </timeWindow>
                   </timeWindows>
              </service>
              <service id="pick3" type="pickup">
                   <location>
                        <id>C1</id>
                        <coord x="-250.0" y="-433.0"/>
                   </location>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <duration>1000.0</duration>
                   <timeWindows>
                        <timeWindow>
                             <start>0.0</start>
                             <end>82800.0</end>
                        </timeWindow>
                   </timeWindows>
              </service>
              <service id="drop1" type="delivery">
                   <location>
                        <id>A2</id>
                        <coord x="-500.0" y="0.0"/>
                   </location>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <duration>1000.0</duration>
                   <timeWindows>
                        <timeWindow>
                             <start>0.0</start>
                             <end>82800.0</end>
                        </timeWindow>
                   </timeWindows>
              </service>
              <service id="drop2" type="delivery">
                   <location>
                        <id>B2</id>
                        <coord x="250.0" y="-433.0"/>
                   </location>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <duration>1000.0</duration>
                   <timeWindows>
                        <timeWindow>
                             <start>0.0</start>
                             <end>82800.0</end>
                        </timeWindow>
                   </timeWindows>
              </service>
              <service id="drop3" type="delivery">
                   <location>
                        <id>C2</id>
                        <coord x="250.0" y="433.0"/>
                   </location>
                   <capacity-dimensions>
                        <dimension index="0">1</dimension>
                   </capacity-dimensions>
                   <duration>1000.0</duration>
                   <timeWindows>
                        <timeWindow>
                             <start>0.0</start>
                             <end>82800.0</end>
                        </timeWindow>
                   </timeWindows>
              </service>
         </services>
    </problem>

**Comment by oblonski** [comment]
Hi,

PickupService and DeliverService are depot-bounded, i.e. pickupServices
are assumed to be delivered to the vehicle's depot (i.e. vehicle's end
location). Accordingly, deliverServices are assumed to be picked up at
vehicle's start location.
Getting back to your example, the solution must always be
start-deliverService-pickupService-end. If you look into your vehicle
after an activity appeared, you get start (1) - deliverService (0) -
pickupService (1) - end where (x) means capacity utilisation.
What you expect is not necessarily depot-bounded, but en-route pickup
and delivery. Here, you need to define Shipments.

Again: Service (and children) are depot-bounded (either it is loaded at
the depot and stay there until the corresponding activity location OR it
is loaded at activity location and stays there until vehicle's end
location). Shipment are not depot-bounded, but route-bounded. If you
have no further restrictions, you can pickup and deliver shipments at
any position in route as long as the delivery follows the pickup.

You can always replace PickupService by a Shipment that has
pickupLocation=PickupService.getLocation and
deliveryLocation=vehicle.getEndLcoation.

Best
Stefan

Am 10/03/15 um 15:17 schrieb Zach Melamed:

**Comment by zach-m** [comment]
Thanks, it's clearer now. 

What this means, however, is that there's no point in combining `Shipment`s with, say, `DeliveryService`s in the same vrpProblem, as their loads are neither additive nor comparable.

My goal, which I'm beginning to understand is not so simple with Jsprit, is to solve problems where the couriers have already started to follow a previous solution, and are therefore somewhat restricted with what they can do. In such situations:

- vehicles may have ALREADY performed a pickup, and now only need to carry out the dropoff (hence I tried mixing `Shipment` with `DeliveryService`)
- consequently, vehicles may have an initial load (which I couldn't see any support for in Jsprit)
- vehicles may already be on route to one end of a Shipment (either pickup or dropoff), so the first stop must be fixed but the others should be solved optimally (this we discussed in [StackOverflow](http://stackoverflow.com/questions/28894695/impose-order-in-jsprit-with-hardactivityconstraint)) - this one I can force in external intervention by "placing" the vehicle at this fixed location when building the problem.

I guess we just moved from an issue report to a feature request..

All the bullets above are required in ongoing optimization use-cases (as opposed to planning ahead), i.e. Same-Day-Delivery vs Next-Day-Delivery. If you see the value in this, let me know. I might be able to contribute to the effort.

**Comment by oblonski** [comment]
You should be able to model this with jsprit. Try this:
Assume at time t=1 you receive a shipment request (A --> B, q=5) where q is the shipment size. You have 1 vehicle with capacity Q=10 that starts at S. "Optimizing" this should yield S(0) --> [0] pickupShipment(A) [5] --> [5] deliverShipment(B) [0] --> [0]S (I just attached the loads before and after activity in square brackets). 

At time t=4 you receive another shipment request (C --> D, q=7). At this time, your vehicle has already started. Moreover, it has already conducted pickup(A) and is located somewhere between A and B. Make a snapshot of your route here, i.e. your shipment has actually become a DeliveryService. Recall, deliveryServices are depot-bounded, thus implicitly picked up at vehicle's start location (which is here somewhere between A and B). Thus, your initial route should look like this: S[5] --> [5] deliverService(B) [0] --> [0] S and your optimized route containing the requested shipment like this: S[5] --> [5] deliverService(B) [0] --> [0] pickupShipment(C) [7] --> deliverShipment(D) [7] --> S
Let me know if this meets your requirement.

**Comment by zach-m** [comment]
The workaround you're suggesting here works well on this particular example.
Let's change the scenario just a bit: The vehicle has been assigned a shipment (A --> B, q=5) as in your scenario, but is now on his way to A (not B) to perform a pickup.
Next, a new shipment is presented, (C --> D, q=7). How would you pose the problem then, remembering that:
- if the vehicle capacity is Q=10, B must come before C
- if the vehicle capacity is Q>12, C might come before B

Also, it's not clear to me (from your first reply on this thread), whether the sizes in a deport-bound constraint are added to those of the a route-bound constraint. In other words, isn't it possible that in a tour that consists of mixed Services and Shipments, the total load on the vehicle at a certain point would exceed its capacity (even though the constraints hold for Services alone and Shipments alone)?

**Comment by oblonski** [comment]
Where is the capacity constraint problem? Do you have any examples that
reproduces the problem, i.e. that the capacity constraint is broken? If
so, it is definitely a bug which needs to be fixed.

Actually, the great thing is that you do not need to manage this (which
would add a significant amount of complexity to users) since jsprit
keeps track. It has internal load states that also deal with mixed
services and shipments in a route.

> The workaround you're suggesting here works well on this particular
> example.
> Let's change the scenario just a bit: The vehicle has been assigned a
> shipment (A --> B, q=5) as in your scenario, but is now on his way to
> A (not B) to perform a pickup.
> Next, a new shipment is presented, (C --> D, q=7). How would you pose
> the problem then, remembering that:
>
>   * if the vehicle capacity is Q=10, B must come before C
>   * if the vehicle capacity is Q>12, C might come before B
>

Correct. This is managed internally.

> Also, it's not clear to me (from your first reply on this thread),
> whether the sizes in a deport-bound constraint are added to those of
> the a route-bound constraint. In other words, isn't it possible that
> in a tour that consists of mixed Services and Shipments, the total
> load on the vehicle at a certain point would exceed its capacity (even
> though the constraints hold for Services alone and Shipments alone)?
>

This should not be possible. If you find a case, it is a BUG. If you
have doubts, write some unit tests with what you expect and give me a
note if these tests fail.

**Comment by zach-m** [comment]
Sorry Stefan I wasn't understood. I am curious to know how would you pose a VrpProblem with the scenario I presented..

**Comment by oblonski** [comment]
No problem. Let me know if you detected a bug or find smth suspicious or hard to understand.
