### ISSUE TITLE
Jsprit.Builder ignores custom objective function

### ISSUE THREAD

**Issue by J-uge** [jsprit/jsprit#158]
With the new Jsprit.Builder, one can call setObjectiveFunction to assign custom SolutionCostCalculator, but the calculator is not actually used in the optimization. Instead the builder calls getObjectiveFunction to construct the solution calculator.

**Comment by oblonski** [comment]
Thanks. You are right. Look at this issue #155. It has already been fixed. 
The fix is in the master branch and the latest snapshot.
Best Stefan
