### ISSUE TITLE
method getRegretScorer in jsprit.core.algorithm.box.jsprit passes wrong parameter?

### ISSUE THREAD

**Issue by PGWelch** [jsprit/jsprit#164]
Should setDepotDistanceParam be getting another property value?

    private RegretInsertion.DefaultScorer getRegretScorer(VehicleRoutingProblem vrp) {
        RegretInsertion.DefaultScorer scorer;
        scorer = new RegretInsertion.DefaultScorer(vrp);
        scorer.setTimeWindowParam(Double.valueOf(properties.getProperty(Parameter.REGRET_TIME_WINDOW_SCORER.toString())));
        scorer.setDepotDistanceParam(Double.valueOf(properties.getProperty(Parameter.REGRET_TIME_WINDOW_SCORER.toString())));
        return scorer;
    }

**Comment by oblonski** [comment]
Ohh. This is definitely a bug. Thank, Phil.
