### ISSUE TITLE
Time-Window is not considered as Hard constraint

### ISSUE THREAD

**Issue by ayush-eyes** [jsprit/jsprit#166]
I have set the capacity dimensions in the vehicle and time window in the services for the VehicleRoutingProblem. After routing the capacity for the vehicle is considered as hard constraint but the time window constraint is not being fullfiled. How do I add this time-window constraint in my vehicle routing algorithm. The below code is implemented in my system currently.
VehicleRoutingProblem vrp = vrpBuilder.build();
VehicleRoutingAlgorithm vra = new GreedySchrimpfFactory().createAlgorithm(vrp);
vra.setPrematureAlgorithmTermination(new IterationWithoutImprovementTermination(100));
Collection<VehicleRoutingProblemSolution> solutions = vra.searchSolutions();

**Comment by oblonski** [comment]
Hi,
Where and how do you set the time window constraints?
Best
Stefan

Am 03/07/15 um 14:18 schrieb Ayush Prasad:

**Comment by ayush-eyes** [comment]
Thank you so much for the reply.
Actually I haven't set any constraint for time window or vehicle capacity,
but vehicle capacity is automatically considered as hard constraint so I'm
assuming my vehicle routing algorithm is using default constraints(capacity
and time-window constraints). If not how can I add this additional
constraint.

Regard,
Ayush

**Comment by PGWelch** [comment]
Have you set the opening and closing times on vehicles and services? (in the builder classes)
		
        
		Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.Email: info@opendoorlogistics.comLinkedin:  http://uk.linkedin.com/in/welchphilipSkype: opendoorlogisticsTel:  +44 (0) 20 8144 4009Website:  http://www.opendoorlogistics.com
		 ---- On Sat, 04 Jul 2015 14:29:16 +0100  notifications@github.com  wrote ----Thank you so much for the reply.
Actually I haven't set any constraint for time window or vehicle capacity,
but vehicle capacity is automatically considered as hard constraint so I'm
assuming my vehicle routing algorithm is using default constraints(capacity
and time-window constraints). If not how can I add this additional
constraint.

Regard,
Ayush

**Comment by ayush-eyes** [comment]
Hi,
    I have assigned shipments(or services) time-slots within which they
have to be delivered. So when I run the algorithm for a particular
time-slot say 8:00 to 11:00,the algo is run for all the shipments within
this time-slot for that day. The available delivery boy(or vehicle)
capacity for that day is also assigned.
//Below is the code implemented for this
VehicleRoutingProblem.Builder vrpBuilder =
VehicleRoutingProblem.Builder.newInstance();
vrpBuilder.setFleetSize(FleetSize.FINITE);

For capacity :
//Vehicle-Type
VehicleTypeImpl.Builder typeBuilder =
VehicleTypeImpl.Builder.newInstance("vehicle-type-1").addCapacityDimension(0,
vehicleCapacity).addCapacityDimension(1,vehicleVolume).addCapacityDimension(2,
vehicleWeight);
typeBuilder.setCostPerDistance(1.0);
VehicleTypeImpl bigType = typeBuilder.build();
//Vehicle
VehicleImpl.Builder vehicleBuilder =
VehicleImpl.Builder.newInstance("vehicle-" + vehicleNumber);
vehicleBuilder.setStartLocationId("1");
vehicleBuilder.setType(bigType);
Vehicle vehicle = vehicleBuilder.build();
vrpBuilder.addVehicle(vehicle);

For time-slot :
//Service
service = Service.Builder.newInstance(id).addSizeDimension(0,
Integer.parseInt(quantity)).addSizeDimension(1,
Integer.parseInt(packagevol)).addSizeDimension(2,
Integer.parseInt(packagewt)).setLocationId(id).setCoord(Coordinate.newInstance(lat,
long)).setTimeWindow(new TimeWindow(startTime, endTime)).build();
vrpBuilder.addJob(service);

//matrix builder is the distance matrix
vrpBuilder.setRoutingCost(matrixBuilder.build());

VehicleRoutingProblem vrp = vrpBuilder.build();

VehicleRoutingAlgorithm vra = new
GreedySchrimpfFactory().createAlgorithm(vrp);
vra.setPrematureAlgorithmTermination(new
IterationWithoutImprovementTermination(100));
Collection<VehicleRoutingProblemSolution> solutions = vra.searchSolutions();

The problem comes when I increase the capacity of the delivery Boy(or
vehicle), the delivery time exceeds the time-slot given for the shipment(or
service), i.e the delivery boy(or vehicle) reached the last delivery point
at 13:00 for shipments(or services) in the time-slot 8:00 - 11:00.

Thank you in advance.
Regards
Ayush

**Comment by oblonski** [comment]
Which jsprit version do you use? Can you send me the entire problem, or, alternatively, can you reproduce this with a simple example?

**Comment by hope4brym** [comment]
Hello,
I am experiencing this problem also - Vehicle Time Constraint is being violated. Please how has this problem been solved?
Cheers.

**Comment by oblonski** [comment]
Hi,
Please provide me a simple example where time windows are broken. I need to be able to reproduce this. Up to now, I have not been able to do so. Furthermore, I require the jsprit version you use. 
Best, Stefan

**Comment by oblonski** [comment]
@PGWelch Hi Phil, have you already included this bugfix? https://github.com/jsprit/jsprit/issues/146

**Comment by PGWelch** [comment]
Yep this is in the latest build of ODL Studio  - i don't think these people are using ODL Studio though? 
		
        
		
		 ---- On Fri, 24 Jul 2015 10:26:20 +0100  notifications@github.com  wrote ----@PGWelch Hi Phil, have you already included this bugfix? #146

**Comment by hope4brym** [comment]
I am using ODL Studio, which I downloaded 2 days ago. Version 1.3.3

On 24 July 2015 at 10:31, Philip Welch <notifications@github.com> wrote:

> Yep this is in the latest build of ODL Studio  - i don't think these
> people are using ODL Studio though?
>
>
>
> ---- On Fri, 24 Jul 2015 10:26:20 +0100 notifications@github.com wrote
> ----@PGWelch Hi Phil, have you already included this bugfix? #146
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsprit/jsprit/issues/166#issuecomment-124455434>.
>



-- 
Thanks and regards,

Owoyemi Abdulwahab
+44 7443 070507

**Comment by oblonski** [comment]
@hope4brym Don't you use ODL?

**Comment by oblonski** [comment]
If I were you, I would first report it to ODL's issue tracker. If we are sure then that the source is jsprit, we can discuss here.

**Comment by oblonski** [comment]
@PGWelch Are you using your github issue tracker?

**Comment by oblonski** [comment]
@PGWelch or do you have another one and how do you usually deal with these issues?

**Comment by oblonski** [comment]
@ayush-eyes have you ever faced the problem again? If so, would you mind to help us finding it?

**Comment by PGWelch** [comment]
The latest build of ODL Studio is using a jsprit snapshot a few days after bugfix #146. I will upgrade it to a jsprit release some point soon.

My users generally aren't developers and rarely use github, so people report problems via the email bugs at opendoorlogistics.com

@hope4brym can you open the stops and vehicles tables in ODL Studio (tables panel on the left) and inspect your time windows values to ensure the format is correct and they've been loaded into ODL Studio properly? Right-click on the table, edit table schema, then change any time windows to type Time (if their type isn't already Time). If the formatting is correct, this won't affect the values. If the formatting is incorrect, this will set them to empty or similar. Incorrectly formatted time values is an easy way to kill time windows, as they won't be read. Please report back and let us know if this is the problem.

If this doesn't work can you see if you can reproduce the problem using great_circle (straight line) rather than road network distances and then send the Excel and script to the bugs email address? As the graphhopper road network files are huge, it will be easier if we can reproduce this using great_circle and don't need to transfer the graphopper files.

**Comment by ayush-eyes** [comment]
@oblonski I don't have access to the code now. The problem of time-constraint was still there. The algorithm was implemented in the same way as given in the following link:
http://www.massapi.com/source/github/77/19/771905286/jsprit-examples/src/main/java/jsprit/examples/RefuseCollectionExample.java.html#141. 
The jar file was jsprit-core-1.4.jar

**Comment by hope4brym** [comment]
@PGWelch: I've checked the stop and vehicle tables schema and the formats
are TIME. Also, I have used great_circle.

On 24 July 2015 at 12:47, Philip Welch <notifications@github.com> wrote:

> The latest build of ODL Studio is using a jsprit snapshot a few days after
> bugfix #146 <https://github.com/jsprit/jsprit/issues/146>. I will upgrade
> it to a jsprit release some point soon.
>
> My users generally aren't developers and rarely use github, so people
> report problems via the email bugs at opendoorlogistics.com
>
> @hope4brym <https://github.com/hope4brym> can you open the stops and
> vehicles tables in ODL Studio (tables panel on the left) and inspect your
> time windows values to ensure the format is correct and they've been loaded
> into ODL Studio properly? Right-click on the table, edit table schema, then
> change any time windows to type Time (if their type isn't already Time). If
> the formatting is correct, this won't affect the values. If the formatting
> is incorrect, this will set them to empty or similar. Incorrectly formatted
> time values is an easy way to kill time windows, as they won't be read.
> Please report back and let us know if this is the problem.
>
> If this doesn't work can you see if you can reproduce the problem using
> great_circle (straight line) rather than road network distances and then
> send the Excel and script to the bugs email address? As the graphhopper
> road network files are huge, it will be easier if we can reproduce this
> using great_circle and don't need to transfer the graphopper files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsprit/jsprit/issues/166#issuecomment-124497488>.
>



-- 
Thanks and regards,

Owoyemi Abdulwahab
+44 7443 070507

**Comment by oblonski** [comment]
@ayush-eyes ok. thanks. this is a very old version. would you mind to run your example with the latest release or even the latest snapshot? Thanks a lot

**Comment by oblonski** [comment]
Were you able to reproduce it, i.e. still time windows broken?

Am 24/07/15 um 14:46 schrieb hope4brym:
> @PGWelch: I've checked the stop and vehicle tables schema and the formats
> are TIME. Also, I have used great_circle.
>

**Comment by oblonski** [comment]
Still an issue?

**Comment by PGWelch** [comment]
I haven't heard from or received any files from @hope4brym so I would close.
