### ISSUE TITLE
remove string concatenation in logger

### ISSUE THREAD

**Issue by oblonski** [jsprit/jsprit#173]
Expensive string concatenation is done even though log level is not .trace in most cases. Therefore
change for example
logger.trace("ruin: " + job.getId());
to
logger.trace("ruin: {}", job.getId());

Thanks, @HeinrichFilter for detecting.

**Comment by oblonski** [comment]
http://stackoverflow.com/questions/6504407/is-there-a-need-to-do-a-iflog-isdebugenabled-check for more information

**Comment by PGWelch** [comment]
The severity would depend on where this happens in the algorithm. In insertion code, particularly constraint checking code, which is absolute-bottleneck stuff, this obviously can't be present. However if you're only doing it when you ruin a job, it will have negligible impact on the solver speed, and so probably isn't worth removing.

**Comment by oblonski** [comment]
You are right and there are no logging statements in constraints :).
