### ISSUE TITLE
remove long running tests from unit tests

### ISSUE THREAD

**Issue by oblonski** [jsprit/jsprit#178]
or at least seperate them from unit tests

**Comment by oblonski** [comment]
now separated and marked as IntegrationTest

run unit tests:
`cd jsprit-core`
`mvn test`

run integration tests:
`cd jsprit-core`
`mvn integration-test`

**Comment by karussell** [comment]
BTW: If you want to run all of them on travis I think you need to add 'verify' for the integ.tests otherwise a test could fail without being noticed

**Comment by oblonski** [comment]
Did you mean this?
https://github.com/jsprit/jsprit/commit/2ce279d5a53be2cfb02fc804243e915ad444eb78#diff-a99d691bcb33dca9baace7043d02b67eR79

Am 17/09/15 um 16:19 schrieb Peter:

**Comment by karussell** [comment]
Ah, yes I think so. Nice. I always included it in the command line ...
