### ISSUE TITLE
System.exit in next job calculate

### ISSUE THREAD

**Issue by muzuro** [jsprit/jsprit#182]
In jsprit.core.algorithm.recreate.RegretInsertionConcurrent.nextJob(Collection<VehicleRoute>, List<Job>, List<Job>) method there is code:

       catch (ExecutionException e) {
            e.printStackTrace();
            logger.error("Exception", e);
            System.exit(1);
        }

This way, exception in nextJob calculation leads to stopping entire jvm.

**Comment by PGWelch** [comment]
Jsprit should probably just pass the exception onto the client code - system.exit is bad!

**Comment by oblonski** [comment]
ok. understand. any suggestions to handle this? I could throw here an unchecked Exception like `new RuntimeException(e.getCause())` and I could also extend the method with throws Exception. However, then I always need to handle this in every implementation of `AbstractInsertionStrategy`. Ideas?

**Comment by karussell** [comment]
just do do `new RuntimeException(ex)` and do not mark as 'throws Exception' :)

Also create a test to make kind of a contract for this case of an exception or add it in the javadocs.

**Comment by oblonski** [comment]
@karussell so you would prefer the first option: `throw new RuntimeException(ex)` and thus making a checked an unchecked Exception?

**Comment by karussell** [comment]
Yeah, I do not like checked exceptions :) (in only rare cases they are useful IMO)

**Comment by PGWelch** [comment]
I rethrow checked exceptions as unchecked exceptions in ODL Studio, whenever i use anything from a 3rd party library marked as throwing an exception. Checked exceptions are a pain and best avoided in my opinion - you just end up with every function marked as 'throws exception'

**Comment by oblonski** [comment]
tiptop. thanks for you help! :+1:
