### ISSUE TITLE
Semi-bounded time on customer delivery

### ISSUE THREAD

**Issue by frodrigo** [jsprit/jsprit#188]
There are time windows, but in real case you not always have open and close of time windows. Sure you can simulate the missing part, but is preferable to not have a dummy constraint, isn't ?

**Comment by oblonski** [comment]
What do you mean here exactly? Can you make an example?

**Comment by frodrigo** [comment]
I mean "delivery before 8pm"

**Comment by PGWelch** [comment]
Wouldn't you just set your time window from 0 to 8pm (or -Double.MaxValue to 8pm - I'm not sure what the appropriate zero point for start time window is). If you only want an end time you just set the start time to a time before the vehicles start...
		
        
		Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.Email: info@opendoorlogistics.comLinkedin:  http://uk.linkedin.com/in/welchphilipSkype: opendoorlogisticsTel:  +44 (0) 20 8144 4009Website:  http://www.opendoorlogistics.com
		 ---- On Sun, 20 Sep 2015 14:06:08 +0100  notifications@github.com  wrote ----I mean "delivery before 8pm"

**Comment by frodrigo** [comment]
That the point, it's the right way to do like this ?

**Comment by oblonski** [comment]
Thanks @PGWelch. Yes, that is the correct way. However, timeWindow.start cannot be negative, therefore set it 0. I think I can close here?
