### ISSUE TITLE
when working with skills preceding and trailing whitespaces should not matter

### ISSUE THREAD

**Issue by oblonski** [jsprit/jsprit#190]
Currently "drilling-machine" and " drilling-machine" are two different skills. 
This should not be.

**Comment by PGWelch** [comment]
ODL uses the concept of standardising all strings for comparison - see (or copy) std method here https://github.com/PGWelch/com.opendoorlogistics/blob/master/com.opendoorlogistics.core/src/com/opendoorlogistics/core/utils/strings/Strings.java.Strings are converted to lower case, whitespace trimmed from both ends, all other whitespace is converted to a single space (so tabs or double spaces inside the string become a single space).The implementation is efficient  (as odl calls it a lot).Best regards, Phil 
		
        
		Philip WelchOpen Door Logistics LimitedSpecialists in open source solutions for transport logistics.Email: info@opendoorlogistics.comLinkedin:  http://uk.linkedin.com/in/welchphilipSkype: opendoorlogisticsTel:  +44 (0) 20 8144 4009Website:  http://www.opendoorlogistics.com

**Comment by oblonski** [comment]
Thanks, @PGWelch. I now make this:
`skills.add(skill.trim().toLowerCase());`

which does not handle any whitespace within the string. hmm.

**Comment by PGWelch** [comment]
Feel free to copy the ODL implementation into jsprit if that helps.

**Comment by oblonski** [comment]
Thanks a lot, Phil

Am 29/09/15 um 09:20 schrieb Philip Welch:
