### ISSUE TITLE
how to solve the real world distance

### ISSUE THREAD

**Issue by bladeshao** [jsprit/jsprit#192]
Hi,

How to consider the real road distance between two points when use your VRP Algorithm?

**Comment by oblonski** [comment]
Hi,
[This](http://stackoverflow.com/questions/33069451/do-the-jsprit-tsp-and-vrp-solvers-allow-provided-time-and-distance-constraints-b/33103276#33103276) might answer you question.

Best,
STefan 

PS please use the mailing list for such questions
