### ISSUE TITLE
enforce activity order in JSprit

### ISSUE THREAD

**Issue by kelish09** [jsprit/jsprit#193]
Hi,

I have a question, how can I enforce one job/activity to be the first job in my route?

For example, I have 5 stops (A, B, C, D, E). I want to make sure that the route starts with stop "D" first.

I am not sure how to implement it, any help will be appreciated? Thanks!

**Comment by oblonski** [comment]
Please look at the mailing lists (old and new) to find a solution. If not, post your question on the mailing list: https://discuss.graphhopper.com/
