### ISSUE TITLE
Take travel cost matrix into account

### ISSUE THREAD

**Issue by longd3** [jsprit/jsprit#194]
Hi, thank you for all the wonderful work on VRP. 

I am writing to request a new feature to allow setting travel cost matrix among locations. Because in realistic problems, we have to consider delay due to traffic thus VRPTW is much harder to solve. Also, there are terrains that crow fly distances do not apply, i.e broken bridge, divided peninsula, etc

It would be great if you consider extending the work on this, I would be glad to contribute what I could to make it happen.

Thanks!

**Comment by oblonski** [comment]
Hi, Please use the [mailing list](https://discuss.graphhopper.com/) for questions. Thanks.
