### ISSUE TITLE
Bug in the plot (Multiple Depot VRP)

### ISSUE THREAD

**Issue by xiaozheng2013** [jsprit/jsprit#203]
Hi, I found out an issue with the plotting of the map and route for Multiple Depot VRP (actually even more general VRP algorithms), check out the second graph in this example of Multiple Deport VRP(https://github.com/jsprit/jsprit/wiki/Multiple-Depot-VRP), there are at least two points that are marked with (5), same for point (15), (9) and so on. 

I think there must be a small bug somewhere in the Plotter class, can someone help to resolve this issue? 

Thanks.

**Comment by xiaozheng2013** [comment]
You can test the bug using this example: https://github.com/jsprit/jsprit/blob/v1.6/jsprit-examples/src/main/java/jsprit/examples/MultipleDepotExample.java

**Comment by oblonski** [comment]
Hi, it is because the default label is 'size', i.e. it labels the size of each service rather than its 'id'. If you want to change this, do this:

```new Plotter(vrp, Solutions.bestOf(solutions)).setLabel(Plotter.Label.ID).plot("output/p01_solution.png", "p01");```

Do you think it is more intuitive to set the default to id?

**Comment by xiaozheng2013** [comment]
Ah, great, thanks, Oblonski. 
To me, since I want to show the result to people who only want to know which route to go, they would prefer to see label id.
