### ISSUE TITLE
Problem with TimeWindows in problems with Pickups & Deliveries

### ISSUE THREAD

**Issue by winwin-dev** [jsprit/jsprit#212]
Hi,
There seems to be an issue with TimeWindows while running the algorithm using Shipments. In my case, if the TimeWindows are not defined, the algorithm runs perfectly. With Pickup and Delivery TimeWindows defined, however, the algorithm simply returns with all jobs unassigned.

**Comment by oblonski** [comment]
Hi,
Can you please provide a simple example such that we can reproduce your issue?
Best,
STefan

**Comment by larsupb** [comment]
Hi,
I'm also running jsprit on pdp with time windows and i don't have the problem described above. Check your timeWindows, stopTimes, drivingTimes etc.. for validity.

**Comment by winwin-dev** [comment]
Hi @oblonski , @larsupb ,

Thanks for the prompt replies. I think I solved my issue and I guess I opened the issue prematurely. Apologies! Running quite perfectly now. Thanks!
