### ISSUE TITLE
vehicle with same id should not be accepted by the vrp builder

### ISSUE THREAD

**Issue by oblonski** [jsprit/jsprit#213]
https://discuss.graphhopper.com/t/cannot-lock-vehicle-twice/457/2

**Comment by AymanABDELHAMID** [comment]
Hello, I know this is an old bug. However, in the initial solution generated by Jsprit; number of routes > number of vehicles available. Hence, I get the error of "Cannot lock vehicle twice" how can this be avoided? Thanks.
