### ISSUE TITLE
multiple time-windows

### ISSUE THREAD

**Issue by jsprit** [jsprit/jsprit#56]
currently only only one time-window for each job can be assigned. they might have multiple time-windows.

**Comment by demonicmetalcs** [comment]
Is there a estimated date when this will be done?
And is there a temp solution to accomplice 2 time windows for a service ?

**Comment by oblonski** [comment]
That will be one of the next features. Conceptually it has already been thought through. It "only" needs to be implemented and tested.

**Comment by apoorv2203** [comment]
Please let me know whats the status of this. If not what is the workaround to achieve this. A sample code would really help

**Comment by demonicmetalcs** [comment]
What is the status of this?

**Comment by oblonski** [comment]
Still under development ... 

Am 26/10/15 um 12:19 schrieb demonicmetalcs:

**Comment by apoorv2203** [comment]
Any pointers on how to implement a workaround for this, or solve this.

**Comment by apoorv2203** [comment]
any updated on this. When do we plan to have this feature

**Comment by oblonski** [comment]
Are you willing to help verifying the new feature "multiple time windows"? I recently implemented it, but still trying to verify whether the results are reasonable. Since benchmarking problems are rare, it is not that easy. So it would be great, you try it out and give some feedback.
I will be pushing the new developments in a seperate branch.

**Comment by oblonski** [comment]
here is the new feature:
https://github.com/jsprit/jsprit/tree/multiple-tws

and here you can find an example:
https://github.com/jsprit/jsprit/blob/multiple-tws/jsprit-examples/src/main/java/jsprit/examples/MultipleTimeWindowExample.java

https://github.com/jsprit/jsprit/blob/multiple-tws/jsprit-examples/src/main/java/jsprit/examples/MultipleTimeWindowExample2.java

It would be great you can find a way to verify the results and give feedback.

**Comment by apoorv2203** [comment]
Great. Thanks. I will verify it.

**Comment by oblonski** [comment]
To get the latest developments when it comes to multiple time windows, follow [this](https://discuss.graphhopper.com/t/need-help-to-verify-multiple-time-window-feature/360) discussion.

**Comment by oblonski** [comment]
in latest release
